### ISSUE TITLE
interweaving diversity

### ISSUE THREAD

**Issue by danielskatz** [si2-urssi/plan#100]
Will diversity efforts be interwoven throughout the project? If so, how?

I will work on a start at this today, specifically

* fellowships - save some for diverse participants - can do the same in education - maybe incubator as well
* require use diversity statement in these cases
* diversity officer in management section

**Comment by JeffCarver** [comment]
@danielskatz as you are editing, if it is easy to do all at once, please feel free to edit directly the Education section (or at least suggest edits).

**Comment by danielskatz** [comment]
I will do so

**Comment by danielskatz** [comment]
done in #106 other than that @sandragesing needs to update the figure of the team in chapter 8 to include the diversity officer

**Comment by sandragesing** [comment]
I updated the figure.
