### ISSUE TITLE
Research on Open Source and Diversity

### ISSUE THREAD

**Issue by JeffCarver** [si2-urssi/plan#11]
TODO item in paragraph that starts on line 99 of the introduction: 

I have some research in this direction and will look for some references and text to strengthen this bullet point. See Section II.B of this paper for some text that could potentially be adapted (http://carver.cs.ua.edu/Papers/Conference/2019/2019_ICSE_FLOSS-Gender.pdf)

**Comment by danielskatz** [comment]
Can you suggest a change via a PR?

**Comment by JeffCarver** [comment]
Added a pull request to address this issue.

**Comment by danielskatz** [comment]
https://github.com/si2-urssi/plan/pull/24 should either close this or be a first step towards improving this part of the plan
