### ISSUE TITLE
Meta issue: Write guidelines to review

### ISSUE THREAD

**Issue by karthik** [si2-urssi/plan#15]
Tell reviewers how to review
- issues first if they are GitHub savvy
- Otherwise hypothesis

**Comment by nniiicc** [comment]
Please provide feedback in the following ways:
1. You can annotate the plan directly. Simply highlight a section and leave a public comment. (note: We are using hypothesis - a web based annotation tool. You do not need to install anything or log-in to leave a public comment)  
2. If you would like to open a discussion about a particular topic please file a github issue https://github.com/si2-urssi/plan/issues and select the appropriate section label.
