### ISSUE TITLE
Strange bullet in list in Chapter 6

### ISSUE THREAD

**Issue by kyleniemeyer** [si2-urssi/plan#26]
The last numbered item at the end of the [Chapter 6](https://github.com/si2-urssi/plan/edit/master/06-Education_training.Rmd) intro has a bullet that appears at the same level in the published report:

```
5. Compile and maintain a body of knowledge of best practices for research software development 

  *  this URSSI activity will seek to aggregate both existing practices, and serve as an outlet 
  for emerging practices from other domain-specific software institutes (e.g., MolSSI, SGCI, IRIS-HEP) 
```

Since none of the other items have bullets, it should probably just be included in the item somehow, or in the text after the list.

**Comment by danielskatz** [comment]
fixed - thanks!
