### ISSUE TITLE
update NSF report in ref?

### ISSUE THREAD

**Issue by danielskatz** [si2-urssi/plan#28]
In chapter 1, we reference
> @techreport{NSF2017,
  author = {{National Science Foundation}},
  title = {Women, Minorities, and Persons with Disabilities in Science and Engineering},
  booktitle = {NSF 17-310},
  year={2017},
  url={https://www.nsf.gov/statistics/2017/nsf17310/},
}

There is also a 2019 version of this - should we reference that one instead?

**Comment by JeffCarver** [comment]
I was not able to find the data in the 2019 report. The last data I see (even in an updated report from the NSB is still from 2017). So, I think we just leave it as it is.
