### ISSUE TITLE
feedback on plan

### ISSUE THREAD

**Issue by danielskatz** [si2-urssi/plan#32]
From Michelle Barker:

* needs clarity on whether you're targeting researchers who code a bit, and/or people employed full-time to support researchers in software engineering. Different parts vary in their statement on this (see comments in text)
* somewhere I'd include a simply diagram that shows the main elements of URSSI/software sustainability eg sustainability box at top, going to 3 boxes below that show software, people policy (or whatever). I think a visual would help people understand that in URSSI's case, these are the elements defining sustainability. Because in other worlds sustainability would be an element used to define software (along with preservation, citation etc). 
* education and training approach - be clear on why you're going to provide a 5 day course? Why is this an impactful thing to do? Is it going to be THE landmark course in the area or a key part of the fellows program? These are valid reasons to do it, having a seminal courses can help raise the profile of software training, and give URSSI a solid outcome with good publicity. But in the text the emphasis is on expanding access to training, and this course will only train a very small amount of people. If you are trying to increase amount of training overall please instead consider coordinating across the sector, with ADSA and RSE-US and others, who already provide a lot of training. I'd also encourage consideration of what [EOSC WG](https://www.eoscsecretariat.eu/working-groups/skills-training-working-group) on skills and training is up to (which handily, I can provide, also see the attached ppt) eg 1) the emerging concept of competency centres that EOSC will further  ie FAIRsFAIR [D6.1 report](https://doi.org/10.5281/zenodo.3549790) and [FAIRsFAIR D6.2](https://zenodo.org/record/3732889) (could URSSI facilitate development and application of this framework in US) 2) the need for coordination across/more training registries (see also similar RDA ETHRD IG on '[Training materials repositories](https://docs.google.com/document/d/1enfT2t97C7PSRnNqDeeeztLeiRiUQZPcy2HcAAgUK7A/edit?usp=sharing.)/portals' including agreed metadata for training repos. Also the focus on development of an international curriculum for data stewardship (I think this is being led by FAIRSFAIR but I might be wrong) (should URSSI lead dev of a curriuclum for RSEs in US?)

And FYI on metrics/indicators to support new career paths, RDA is getting into this. [...] [OSPP report](https://ec.europa.eu/research/openscience/index.cfm?pg=open-science-policy-platform) [...] the current vision seems to be focused on a registry of different indicators.

> [1 of 5 attributes needed to further open science]: An academic career structure that fosters outputs¨ practices and behaviours to maximise contributions to a shared research knowledge system. To this end¨ in discussion with the OSPP¨ the Research Data Alliance has committed to spearhead a new collaborative platform3 to share both the intention and outcomes of pilots and other initiatives taken by different actors that specifically address the academic reward system. All Member States will have the opportunity to contribute to this so that everyone can benefit from the innovation of others by sharing.

**Comment by karthik** [comment]
I opened her comments as individual issues. Can we close this and open single item issues for anything I've missed?

**Comment by JeffCarver** [comment]
Fine by me.

**Comment by danielskatz** [comment]
Sure, though I think we have captured or completed them all.

**Comment by karthik** [comment]
ok I'll close this then.
