### ISSUE TITLE
mission statement change?

### ISSUE THREAD

**Issue by danielskatz** [si2-urssi/plan#34]
The current mission statement is: 

> Our mission is to improve the recognition, development, and use of software for a more sustainable research enterprise. We achieve this mission through collaboratively developing education, outreach, and software services that emphasize open, transparent reproducible, and cooperative practices. URSSI is an institute for software expertise as well as a social infrastructure that promotes an inclusive and diverse community of research software engineers, maintainers, contributors, and users.

Andrew suggested that we should expand what "recognition [of software]" means in concrete terms.  He specifically suggested changing the first sentence to the following:

> Our mission is to improve the status of software as a key element of a more sustainable research enterprise. This includes enhancing recognition of its importance by all stakeholders, improving its development practices, and increasing its use.

**Comment by JeffCarver** [comment]
I was not in the group that developed the mission statement, so take this comment with that caveat, but the change sounds like a good suggestion to me.

**Comment by danielskatz** [comment]
I'm assigning this to Karthik as the "owner" of the process that developed this but it would be good to also get feedback from @sandragesing and @nniiicc

**Comment by nniiicc** [comment]
I don't have strong feelings - but this edit shifts the statement from being encapsulated in a single sentence to using multiple sentences of explanation... If others feel that this sentence "Our mission is to improve the status of software as a key element of a more sustainable research enterprise" defines the mission of URSSI - as a standalone (unqualified) sentence then thats fine for me.

**Comment by danielskatz** [comment]
thanks @nniiicc - I agree with you, but also realize that as originally written, we don't really say who should recognize software more.  Maybe it's ok to leave this vague.

**Comment by karthik** [comment]
I agree with @nniiicc

The mission statement needs to be clear and concise and is typically a one-sentence statement describing why the org exists.  It doesn't have to be exhaustive and cover everything.

I am fine with changing it to:

> Our mission is to improve the status of software as a key element of a more sustainable research enterprise

The second sentence

> This includes enhancing recognition of its importance by all stakeholders, improving its development practices, and increasing its use.

feels overly descriptive for a mission statement. We can make sure to clarify this elsewhere.

**Comment by sandragesing** [comment]
I would also prefer to have a clear and concise one-sentence statement as suggested by @karthik 

We can go into more detail in a description.

**Comment by danielskatz** [comment]
The statement we started with is

> Our mission is to improve the recognition, development, and use of software for a more sustainable research enterprise.

We are now saying we want to change this to

> Our mission is to improve the status of software as a key element of a more sustainable research enterprise

?

**Comment by karthik** [comment]
The new one still doesn't sit well with me. It's less direct, and less impactful, neither of which are suitable for a mission statement.  The new version also removes development (i.e. the people who are building this) and folds it under status of software, which also feels less impactful.

**Comment by danielskatz** [comment]
I agree, that's why I made my previous comment.  I accept Andrew's point, but don't see a better option.

**Comment by karthik** [comment]
In that case let's leave it as is
