### ISSUE TITLE
Align introduction and 3.3

### ISSUE THREAD

**Issue by karthik** [si2-urssi/plan#39]
*Such people often lead double lives, working tirelessly to meet the traditional responsibilities of academic life, while developing open source tools that enable modern research. We are able to break the problem down into the following four areas:*

> Can these four areas align with the three areas in 3.3 desire impact (software, people, ecosystem)?

 _1.4 What we plan to do and why_

> Can the four 4 things you plan to do map against the 4 challenges identified earlier, and the 3 focus areas in 3.3?

**Comment by karthik** [comment]
This is currently 3.3.

For **software**, URSSI aims to improve the sustainability of research software by

Developing and sharing good-enough and best practices for software projects, including for testing, governance, codes of conduct, continuous integration

Documenting sustainability models and providing guidance on how to choose among them

Promoting communities and appropriate governance models for open source research software

Building models to make best use of and support transient software contributors (e.g. students)

For **people**, URSSI aims to improve the careers of those who develop and maintain research software by:

Promoting new career paths for those who develop and maintain research software

Developing and advocating for research software usage and impact metrics to be a factor in the hiring and promotion of software developers and maintainers

Promoting the publication of research software

Coordinating community efforts, including by URSSI, to create and provide training for those who want to develop and maintain research software

Encouraging a diverse set of participants to enter the research software development and maintenance field and decreasing structural and systemic barriers to productive careers for members of underrepresented groups

For the **research software ecosystem**, URSSI aims to improve the understanding and functioning of the ecosystem by

Documenting the use of research software in research and providing systematic and regular analysis of the impact this software has on research

Growing and participating in communities around the field of research software

Promoting an increased understanding of the importance of research software in research

Promoting software credit and citation mechanisms

Studying and disseminating methods to catalog and promote research software

Supporting the use of software in reproducibility

----

The four areas in the introduction described in the intro are Incubator, Education + training, Policy and Community.  It's hard to achieve 1:1 mapping.


![image](https://user-images.githubusercontent.com/138494/85061597-f5ab3580-b15b-11ea-8b2c-8d59fac36119.png)

**Comment by karthik** [comment]
Im not sure how to proceed. 3.3 described a longer set of concrete activities. The intro talks more broadly about 4 action areas.

**Comment by danielskatz** [comment]
I don't think this mapping is needed or really helpful.  I understand the idea might make sense generically, but I don't think it does here.  I wonder if it would be better to add a general statement saying that most of our proposal activities has aspects that contribute to all three goals

**Comment by karthik** [comment]
Correct, that's my point.

**Comment by danielskatz** [comment]
so it seems like that's how we could proceed then - add a general statement.  Or am I missing something? (I'm confused by the blocked label)

**Comment by karthik** [comment]
I'm trying to get the introduction finished by my deadline of the 19th. If I don't have a clear path forward I add the blocked label.
