### ISSUE TITLE
Narrow down scope

### ISSUE THREAD

**Issue by karthik** [si2-urssi/plan#40]
_While The Carpentries, for example, does an excellent job of teaching basic programming and computational & data analytic methods to researchers in a peer-to-peer model, mostly in 2-day courses, URSSI could fill the gap in teaching more in-depth software engineering_

> URSSI may provide some training in this area, but cannot hope to meet the needs of all US researchers, so better to identify a VERY SMALL niche that URSSI will teach in, and/or focus on the MANY other training initiatives in research institutions, by publishers, by commercial providers, by other grassroots organisations (eg RDA/CODATA summer schools (although these probably aren't on software) and disciplinary activities (eg ELIXIR).

**Comment by karthik** [comment]
I think URSSI is already doing this and it's not clear to me if Michelle is asking us to communicate this better or actually change our niche.  Right now we're saying that The Carpentries have the _using research software tools_ market, [the RDA codata summer school ](https://codata.org/initiatives/strategic-programme/research-data-science-summer-schools/)has a very similar niche.  Ours is quite different and fills a need that does not exist. University courses in SWE are more theoretical and less applied and also inaccessible to domain researchers. We are offering something that doesn't just scratch the surface (a webinar or 2 day event) but aims to go deeper and allow researchers to incorporate these techniques into their own work.

**Comment by karthik** [comment]
@danielskatz  Thoughts? Not sure if Michelle is on GitHub to tag her.

**Comment by danielskatz** [comment]
I agree with your point.  (And I think Michelle is not yet on GitHub)

**Comment by karthik** [comment]
I finessed this a bit more but don't see further action necessary at this time. I'll close the issue for now, but happy to resurrect at a future stage of the review.
