### ISSUE TITLE
Post high res diagram on the website

### ISSUE THREAD

**Issue by karthik** [si2-urssi/plan#48]
> Chapter 2: I realise that this might not be anything like the typeset form of this document but, just in case, I’d make the diagram on this page much bigger – maybe give it its own page. It’s really impactful, but a bit small!

If Dan can share the higher resolution version, we can link to the file and leave it in the same repository.

**Comment by danielskatz** [comment]
I think this is already on website - see https://plan.urssi.us/images/conceptualization_activities.jpg

**Comment by danielskatz** [comment]
👋 @karthik - can you go ahead and create the link you are thinking of?
