### ISSUE TITLE
Converting Google Docs to Markdown. 

### ISSUE THREAD

**Issue by nniiicc** [si2-urssi/plan#5]
There are a few ways to do this:

1. Copy and Paste
2. Download a document and pass it through pandoc
3. Use this [script](https://medium.com/@vladimir.simovic/convert-html-and-documents-from-google-docs-to-markdown-752aeb7f0f0f) following directions [here](https://medium.com/@vladimir.simovic/convert-html-and-documents-from-google-docs-to-markdown-752aeb7f0f0f) ... A markdown doc will be emailed to you. 

Benefits to 2 and 3 are that it gives you a good base to edit the Markdown

**Comment by karthik** [comment]
I added some instructions on a add in in the README.
