### ISSUE TITLE
Sharing education content

### ISSUE THREAD

**Issue by JeffCarver** [si2-urssi/plan#61]
Comment from Wolfgang on the 5 items listed just before 6.1 that we plan to do.

Where do you plan to publish these resources? I think it would be very useful to strike up a collaboration with the Carpentries for them to host the outcomes of #2 at least.

**Comment by JeffCarver** [comment]
I am not sure what we can say regarding sharing the content developed as part of the Education activities. Wolfgang suggests that we collaborate with the Carpentries. I'm not sure that we can commit to that in the document. One option would be to add an item 6 in section 6.3 as a "Packaging and Sharing" activity where we can commit to packaging and sharing the content developed through existing repositories like The Carpentries. But, I'm not even sure if it is ok to mention that. Thoughts?

**Comment by danielskatz** [comment]
Why can't we say that we will make the materials public on GitHub at the least? And then go a little further and say that we will provide them in the style of Carpentries lessons?  And then say we will seek to work with the Carpentries to have them included as Carpentries content?

**Comment by karthik** [comment]
I think we can say that we’ll follow the best practices we preach. All material will be on Github and each release will be archived on Zenodo with a proper license that allows anyone to use and remix the content.

**Comment by JeffCarver** [comment]
We already say in item 1 that we will package them. Does it make sense to add an item 6 that covers what @danielskatz and @karthik say above? If so, I'll draft one in a pull request for you to review.

**Comment by karthik** [comment]
Sure, adding item 6 is good. Happy to review.

**Comment by danielskatz** [comment]
I agree

**Comment by JeffCarver** [comment]
I made this change and created a pull request.
