### ISSUE TITLE
Is Research Project Carpentry out of scope?

### ISSUE THREAD

**Issue by JeffCarver** [si2-urssi/plan#64]
Comment from Wolfgang on the last line of 6.2.2 that "URSSI will not have the bandwitdh to perform all of the work.

That's a tricky statement to make, because on the one hand we hope to convince reviewers to give us money for the activities outlined herein, but on the other hand we're saying that we will not actually be able to do the work outlined herein.

I get that seeking external funding is good, but it's a thin line. It may be better to state this in the form "We will work on a rudimentary version of this training module, and seek additional outside funding to flesh it out into a complete curriculum" or something similar.

**Comment by danielskatz** [comment]
It might be better just to leave off the end, and change this sentence to:
> URSSI will lead this work, organizing a community that will include external participants.
