### ISSUE TITLE
Clarify text in Section 1

### ISSUE THREAD

**Issue by JeffCarver** [si2-urssi/plan#8]
On line 20 of the section 1 file, the second sentence says "Research software is often not cited (31-43%) ...". In reading the sentence, it is not clear what the numbers in parentheses represent.

**Comment by danielskatz** [comment]
This is now line 83...

**Comment by danielskatz** [comment]
@karthik - feel free to close this if you think it's already been addressed...

**Comment by JeffCarver** [comment]
Yes, it looks to have been fixed. I no longer see the placeholder in the text online. So, I am closing the issue.
