### ISSUE TITLE
Chapter 5 general comments

### ISSUE THREAD

**Issue by tracykteal** [si2-urssi/plan#80]
Comments on Chapter 5 of the plan. 

I like the distinction between 'research' and 'advocacy' plans and clearly identifying key challenges/changes that this area is focusing on. 

- There are 6 'changes' listed at the beginning and 7 'challenges' in 5.2.1. There are similarities in the two lists and the actions map to the 'challenges'. How are the changes and the challenges related?
- There may be a reason it's constructed this way, but it seems that Aims are more standard than Challenges. Could you rewrite the 7 challenges as Aims. And then in the Activities section refer to those aims and how the activities help achieve those aims. 
- The activities do refer to the challenges in the title, but it's not easy to remember those challenges when reading the activities to know what they're referring to. Rather than ordering by 'Research' or 'Advocacy', could you order by Challenge/Aim and list both types under that category. It could make the link between goals and activities more direct.
- Overall there are a lot of planned activities! Many of those activities have short proposed timelines. e.g. "Create checklists/review guidelines for different levels of peer-review for software; can be tiered, could issue stars or use another rating system; leverage information already available from journals and other resources. (1 week)" or are very broad "e.g. create a mentoring program". While it's great to be ambitious, it could also strike a reviewer as not being realistic or somewhat unfocused, or just seem like a laundry list. Is there a way to identify the key priorities for a reviewer?
- Because many of the activities are very broad, it still doesn't necessarily address the 'how will they do it' for a reviewer. It would be difficult to scope out each in the list, but perhaps this is more reason to reduce or prioritize the list.

- In the Events and Travel section, you could consider online events as that will likely continue to be a way that people can and may prefer to engage.

**Comment by danielskatz** [comment]
6th point addressed in https://github.com/si2-urssi/plan/commit/66d81f9deb9fb645c29de5e1b128476a3a9dd4b5

**Comment by danielskatz** [comment]
re 2nd point, challenges renamed as aims in https://github.com/si2-urssi/plan/commit/128970d4b762b477c9d62bdb794a650ddb1a5ddf and rephrased in https://github.com/si2-urssi/plan/commit/0579e1317a816ffe54fb5ace91fa3ba503b0e052

**Comment by danielskatz** [comment]
1st point addressed in https://github.com/si2-urssi/plan/commit/ac191e891c47aa9b9befdfd8a26b53f8dd28f0f1

**Comment by danielskatz** [comment]
3rd point addressed in https://github.com/si2-urssi/plan/commit/e83eb9351c37a222cd92f4c9247ce63c2c98f195 - This also finishes addressing 2nd point, I think

**Comment by danielskatz** [comment]
Re 4th point

> Overall there are a lot of planned activities! Many of those activities have short proposed timelines. e.g. "Create checklists/review guidelines for different levels of peer-review for software; can be tiered, could issue stars or use another rating system; leverage information already available from journals and other resources. (1 week)" or are very broad "e.g. create a mentoring program". While it's great to be ambitious, it could also strike a reviewer as not being realistic or somewhat unfocused, or just seem like a laundry list. Is there a way to identify the key priorities for a reviewer?

This is not a proposal as it doesn't have a budget envelope it is working to fit in, so at this point, I don't want to remove things. I agree that is a bit of a laundry list, and will think about how we could prioritize them, though this somewhat assume knowledge of a solicitation that doesn't yet exist and the potential funder's goals.

**Comment by tracykteal** [comment]
Like the updated structure. Thanks!

**Comment by danielskatz** [comment]
It's great to get quick feedback - thanks!

**Comment by danielskatz** [comment]
Initial prioritization done via adding "(+)" to some activities. Also added some text about this.  All in https://github.com/si2-urssi/plan/commit/81658ee46a7a3419762eb451ef7774dcc98607a7 (which also includes a bunch of other fixes, sorry...)

**Comment by danielskatz** [comment]
I think I've addressed all the points but the 5th:

> Because many of the activities are very broad, it still doesn't necessarily address the 'how will they do it' for a reviewer. It would be difficult to scope out each in the list, but perhaps this is more reason to reduce or prioritize the list.

which I would like to ignore for now.  I agree this is an issue, but given a fixed page budget for a proposal, I'm not sure how to address it

**Comment by danielskatz** [comment]
@tracykteal - Thanks very much for your comments and feedback.

Please let me know what you think at this point.

Is there more you think should be done?  Or can I close this issue?

**Comment by tracykteal** [comment]
Thanks @danielskatz. I agree from your comments that at this stage it's good to include a longer list. Adding some prioritization and the re-arrangement helps understand how they all fit in context. Thanks for the updates! I think this issue can be closed.

**Comment by danielskatz** [comment]
thanks for your help again!
