### ISSUE TITLE
Need citation

### ISSUE THREAD

**Issue by karthik** [si2-urssi/plan#87]
> very few train researchers in modern open source software development

Do you have references to any studies that give a sense of the numbers here?

@danielskatz Do you have any that come to mind? Isn't this a key argument we make often, that researchers are not trained in best practices.

**Comment by danielskatz** [comment]
The UK and US surveys of developers that Simon and I did, I think

**Comment by karthik** [comment]
Is this it? 
https://zenodo.org/record/2585783

```
@software{olivier_philippe_2019_2585783,
  author       = {Olivier Philippe and
                  Martin Hammitzsch and
                  Stephan Janosch and
                  Anelda van der Walt and
                  Ben van Werkhoven and
                  Simon Hettrick and
                  Daniel S. Katz and
                  Katrin Leinweber and
                  Sandra Gesing and
                  Stephan Druskat and
                  Scott Henwood and
                  Nicholas R. May and
                  Nooriyah P. Lohani and
                  Manodeep Sinha},
  title        = {{softwaresaved/international-survey: Public release 
                   for 2018 results}},
  month        = mar,
  year         = 2019,
  publisher    = {Zenodo},
  version      = {2018-v.1.0.2},
  doi          = {10.5281/zenodo.2585783},
  url          = {https://doi.org/10.5281/zenodo.2585783}
}
```

**Comment by danielskatz** [comment]
No, I was thinking of the UK blog/data:
* @Hettrick-blog -   S. Hettrick, “It's impossible to conduct research without software, say 7 out of 10 UK researchers,” Software Sustainaiblity Institute, 2014. Available at: https://www.software.ac.uk/blog/2016-09-12-its-impossible-conduct-research-without-software-say-7-out-10-uk-researchers
* @hettrick2014 - S.J. Hettrick, M. Antonioletti, L. Carr, N. Chue Hong, S. Crouch, D. De Roure, et al, “UK Research Software Survey 2014”, Zenodo, 2014. http://doi.org/10.5281/zenodo.14809 

and the US paper/data:
* @nangia_katz_2017 - U. Nangia and D. S. Katz, “Track 1 Paper: Surveying the U.S. National Postdoctoral Association Regarding Software Use and Training in Research,” WSSSPE5.1, 2017. http://doi.org/10.6084/m9.figshare.5328442.v1
* [not yet in the references] Udit Nangia, & Daniel S. Katz. (2017). Survey of National Postdoctoral Association - Dataset [Data set]. Zenodo. http://doi.org/10.5281/zenodo.843607

**Comment by danielskatz** [comment]
Also, the ref you just added as olivier_philippe_2019_2585783 was already there as @rse-survey
