### ISSUE TITLE
Section 1 - missing citation

### ISSUE THREAD

**Issue by JeffCarver** [si2-urssi/plan#9]
Line 20

**Comment by danielskatz** [comment]
I'm not sure what specifically is missing

**Comment by JeffCarver** [comment]
Line 94 of 01-intro.Rmd has something that says '[citation]'. I assumed that meant a citation was supposed to go there. But, maybe I misunderstood.

**Comment by karthik** [comment]
This is a known issue (that's why I left the placeholder for a future edit). Same with anything marked TODO. I wasn't looking to turn these into issues yet.

**Comment by JeffCarver** [comment]
No problem. I just noted that it was still something to be fixed. I didn't see a TODO on it. So, feel free to close the issue if you don't want it here. I was just doing what Dan asked.

**Comment by danielskatz** [comment]
Can we close this one?  I am also unsure what line 20 was at this point.

**Comment by JeffCarver** [comment]
This issue has been addressed. I no longer see the missing citation.
